python3 train_ssd.py \
    --pretrained-ssd=models/mb2-ssd-lite-mp-0_686.pth \
    --net=mb2-ssd-lite \
    --dataset-type=voc \
    --data=data/voc \
    --model-dir=models/output \
    --num-workers=8 \
    --batch-size=16 \
    --num-epochs=56 \
    --t-0=8 \
    --validation-epochs=1 \
    --lr=0.0001 \
    --extra-layers-lr=0.001 \
    --base-net-lr=0.000001 \
    --weight-decay=0.000001 \
    --validation-mean-ap \
    --scheduler=cosine-warmrestart \
    --no-augment